### ISSUE TITLE
JVMMemoryPressure - should it be set to >=95% or >=80% ?

### ISSUE THREAD

**Issue by eladrkatz** [ev2900/OpenSearch_CloudWatch_Alarms#3]
According to https://docs.amazonaws.cn/en_us/opensearch-service/latest/developerguide/cloudwatch-alarms.html
The settings for the JVMMemoryPressure alarm should be >=95% and not >=80%

**Comment by ev2900** [comment]
Good find @eladrkatz according to the documentation _OldGenJVMMemoryPressure_ should be >=80% and otherwise JVMMemoryPressure should be >=95%

Let me look into what is considered _OIdGen_ and start working on fix

**Comment by ev2900** [comment]
I added input parameters you can set if you are / are not using older generation instances. 

If you indicate you are using older generation instances the memory thresholds will be set at >=80%. If you indicate you are using current generation instances the memory thresholds will be set at >=95%

![image](https://user-images.githubusercontent.com/5414004/194143060-92af220a-4728-472e-a3f5-64412cd8eb3f.png)

**Comment by eladrkatz** [comment]
thanks!
