### ISSUE TITLE
Missing recommended alarm definitions

### ISSUE THREAD

**Issue by petro2050** [ev2900/OpenSearch_CloudWatch_Alarms#4]
I was looking at https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html and noticed this repo is missing `Nodes`, `5xx`, `ThreadpoolSearchRejected`, and `ThreadpoolWriteRejected` alarm definitions. Can you please add them and update the table in the readme?

Another problem I saw is the above link has `MasterOldGenJVMMemoryPressure`, but you have `OldGenMasterJVMMemoryPressure` here.

`ClusterStatus.yellow` evaluation period should be 5 times instead of 1.

**Comment by ev2900** [comment]
Thanks. I'll take a look at this and update this issue shortly

**Comment by ev2900** [comment]
I updated the [read me](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/README.md) and [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml) to reflect `ClusterStatus.yellow` evaluation period of 5 times instead of 1

**Comment by ev2900** [comment]
I updated `OldGenMasterJVMMemoryPressure` in the [read me](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/README.md) to `MasterOldGenJVMMemoryPressure` 

No change is required in the [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml). The [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml) monitors the metric `MasterJVMMemoryPressure` which will report the master JVM memory pressure regardless of if it is a previous or current generation instance. The logic to adjust the thresholds for current generation vs previous generation instances is already in the [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml)

**Comment by ev2900** [comment]
I added to the [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml) alerts for

* ThreadpoolSearchRejected maximum is >=1 for 1 minute, 1 consecutive time 
* ThreadpoolWriteRejected maximum is >=1 for 1 minute, 1 consecutive time

I updated the table in the [read me](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/README.md) to include these

**Comment by ev2900** [comment]
I added to the [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml) alerts for 

* Nodes minimum is < x for 1 day, 1 consecutive time

This required adding an additional input parameter in the [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml). The parameter is `NumberOfNodesInCluster ` when you deploy the [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml) you will be asked for the value of this additional parameter

**Comment by ev2900** [comment]
Looking into the _5xx alarms >= 10% of OpenSearchRequests_ I will not be able to add this to the [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml) . I am not seeing a way to calculate _10% of OpenSearchRequests_ for use in the alarm

**Comment by petro2050** [comment]
Thanks @ev2900!

I think another discrepancy is `JVMMemoryPressure` on the AWS doc is for 60 seconds instead of 300.

**Comment by ev2900** [comment]
I reopened the issue. Let me check

**Comment by petro2050** [comment]
Thanks! 

- `OldGenJVMMemoryPressure` should be 60 seconds.
- `MasterJVMMemoryPressure` should be 60 seconds with 3 evaluations.
- `MasterOldGenJVMMemoryPressure` should be 60 seconds with 3 evaluations.

**Comment by ev2900** [comment]
Good catch @petro2050 . I changed `JVMMemoryPressure` and `MasterJVMMemoryPressure` period to 60 seconds. 

I updated both the [read me](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/README.md) and the [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml)

Thanks for pointing out these issues @petro2050 I appreciate it. Let me know if you find any other mistakes. It looks like the AWS documentation regarding the recommended metrics changed a bit since I first created [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml)

**Comment by petro2050** [comment]
Thanks for the update. It looks like two items still need to be updated:

- `MasterJVMMemoryPressure` should be 3 evaluations
- `MasterOldGenJVMMemoryPressure` should be 3 evaluations

**Comment by ev2900** [comment]
Thanks. I update [CloudFormation stack](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/OpenSearch_cloudwatch_alarms.yaml) so `MasterJVMMemoryPressure ` is 3 evaluations.

Let me know if you don't see it

**Comment by petro2050** [comment]
Oh, I meant the readme isn't updated. :)

**Comment by ev2900** [comment]
Ok thanks for the clarification. I updated the [read me](https://github.com/ev2900/OpenSearch_CloudWatch_Alarms/blob/main/README.md)
